ip_base_url: "192.168.0.108"
yolo_model: "yolo11n.pt"    # ex) "yolov8n.pt", "yolo11n.pt"
imgsz: 640
conf: 0.4    # default is 0.25
classes:    # https://github.com/ultralytics/ultralytics/blob/9dccbd42298ce801054cb90cd0da0442b2adb10d/ultralytics/cfg/datasets/coco.yaml
  - 39    # bottle
  - 63    # laptop
  - 66    # keyboard
  - 67    # cell pheon
  - 76    # scissors
